# Generated by Django 3.2.13 on 2022-05-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_cases',
            new_name='DB_tool',
        ),
    ]
