# Generated by Django 3.2.13 on 2022-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_db_tool_stime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('body', models.CharField(default='', max_length=1000)),
                ('uid_from', models.CharField(default='', max_length=30)),
                ('ctime', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
