# Generated by Django 3.2.13 on 2022-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_db_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_order',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
